/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietHoaDonDAO;
import DTO.ChiTietHoaDon;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class BanHangJFrame extends javax.swing.JFrame {

    private BanHangJPanel banHangJPanel;

    public JButton getBtnLuu() {
        return btnLuu;
    }

    /**
     * Creates new form BanHangJFrame
     */
    public BanHangJFrame(ChiTietHoaDon cthd, BanHangJPanel banHangJPanel) {
        initComponents();
        setView(cthd);
        this.banHangJPanel = banHangJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinHangHoa = new javax.swing.JPanel();
        jlbMaHH = new javax.swing.JLabel();
        jtfMaHH = new javax.swing.JTextField();
        jlbTenHH = new javax.swing.JLabel();
        jtfTenHH = new javax.swing.JTextField();
        jlbDVT = new javax.swing.JLabel();
        jtfThanhTien = new javax.swing.JTextField();
        jlbGiaBan = new javax.swing.JLabel();
        jtfDVT = new javax.swing.JTextField();
        jlbGiaNhap = new javax.swing.JLabel();
        jlbSoLuongTon = new javax.swing.JLabel();
        jtfSoLuong = new javax.swing.JTextField();
        jtfGiaBan = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinHangHoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hàng hóa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinHangHoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbMaHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaHH.setText("Mã hàng hóa");

        jtfMaHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfMaHH.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfMaHH.setEnabled(false);

        jlbTenHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTenHH.setText("Tên hàng hóa");

        jtfTenHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfTenHH.setEnabled(false);

        jlbDVT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDVT.setText("Thành tiền");

        jtfThanhTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfThanhTien.setEnabled(false);

        jlbGiaBan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaBan.setText("Giá bán");

        jtfDVT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfDVT.setEnabled(false);

        jlbGiaNhap.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaNhap.setText("Đơn vị tính");

        jlbSoLuongTon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSoLuongTon.setText("Số lượng");

        jtfSoLuong.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfSoLuong.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jtfGiaBan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfGiaBan.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfGiaBan.setEnabled(false);

        javax.swing.GroupLayout jpnThongTinHangHoaLayout = new javax.swing.GroupLayout(jpnThongTinHangHoa);
        jpnThongTinHangHoa.setLayout(jpnThongTinHangHoaLayout);
        jpnThongTinHangHoaLayout.setHorizontalGroup(
            jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbMaHH)
                                    .addComponent(jlbTenHH))
                                .addGap(59, 59, 59)
                                .addComponent(jtfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbSoLuongTon)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenHH, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jtfSoLuong))))
                .addGap(30, 30, 30)
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addComponent(jlbGiaNhap)
                        .addGap(46, 46, 46)
                        .addComponent(jtfDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbGiaBan)
                            .addComponent(jlbDVT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfThanhTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jpnThongTinHangHoaLayout.setVerticalGroup(
            jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbMaHH)
                        .addComponent(jtfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbGiaBan))
                    .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenHH)
                            .addComponent(jtfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSoLuongTon)
                            .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbGiaNhap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlbDVT))
                            .addComponent(jtfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );

        btnLuu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-save.png"))); // NOI18N
        btnLuu.setText("Lưu dữ liệu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongTinHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThongTinHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setView(ChiTietHoaDon cthd) {
        jtfMaHH.setText(cthd.getMaHang());
        jtfTenHH.setText(cthd.getTenHang());
        jtfGiaBan.setText(cthd.getDonGia() + "");
        jtfDVT.setText(cthd.getDVT());
        jtfSoLuong.setText(cthd.getSoLuong() + "");
        jtfThanhTien.setText(cthd.getThanhTien() + "");
    }
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        cthd.setMaHang(jtfMaHH.getText());
        cthd.setTenHang(jtfTenHH.getText().trim());
        cthd.setDVT(jtfDVT.getText());
        cthd.setDonGia(Double.parseDouble(jtfGiaBan.getText()));
        cthd.setSoLuong(Double.parseDouble(jtfSoLuong.getText()));
        double ThanhTien = Double.parseDouble(jtfGiaBan.getText()) * Double.parseDouble(jtfSoLuong.getText());
        cthd.setThanhTien(ThanhTien);
        jtfThanhTien.setText(ThanhTien + "");

        for (int i = 0; i < banHangJPanel.listCTHD.size(); i++) {
            ChiTietHoaDon cthdCu = banHangJPanel.listCTHD.get(i);
            if (cthdCu.getMaHang().equals(cthd.getMaHang())) {
                banHangJPanel.listCTHD.set(i, cthd);
                break;
            }
        }

        banHangJPanel.LoadCTHDVaoTable(null, null, null);
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jlbDVT;
    private javax.swing.JLabel jlbGiaBan;
    private javax.swing.JLabel jlbGiaNhap;
    private javax.swing.JLabel jlbMaHH;
    private javax.swing.JLabel jlbSoLuongTon;
    private javax.swing.JLabel jlbTenHH;
    private javax.swing.JPanel jpnThongTinHangHoa;
    private javax.swing.JTextField jtfDVT;
    private javax.swing.JTextField jtfGiaBan;
    private javax.swing.JTextField jtfMaHH;
    private javax.swing.JTextField jtfSoLuong;
    private javax.swing.JTextField jtfTenHH;
    private javax.swing.JTextField jtfThanhTien;
    // End of variables declaration//GEN-END:variables
}
