/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.HangHoaDAO;
import DAO.NhaCungCapDAO;
import DAO.NhomHangDAO;
import DTO.HangHoa;
import DTO.NhaCungCap;
import DTO.NhomHang;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Main.FontOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class HangHoaJFrame extends javax.swing.JFrame {

    private HangHoaJPanel hangHoaPanel;

    public JButton getBtnLuu() {
        return btnLuu;
    }
    /**
     * Creates new form HangHoaJFrame
     */

    int flag = 0;

    public HangHoaJFrame(HangHoa hangHoa, HangHoaJPanel hangHoaPanel, int flag) {
        // Lấy đối tượng cha của JFrame (Dialog)
        initComponents();
        setView(hangHoa);
        this.flag = flag;
        this.hangHoaPanel = hangHoaPanel;
        FontOptionPane.setUIFont();

    }

    public String generateMaHang() {
        HangHoa hanghoa = HangHoaDAO.getInstance().getLastHangHoa();
        int sothutu = (Integer.parseInt(hanghoa.getMaHang().substring(2)) + 1);
        String mahang = "HH";
        if (sothutu < 10) {
            mahang = "HH00";
        } else if (sothutu < 100) {
            mahang = "HH0";
        }
        mahang += sothutu;
        return mahang;
    }

    public void setView(HangHoa hangHoa) {
        if (hangHoa != null) {
            jtfMaHH.setText(hangHoa.getMaHang());
            setComboBoxNHH(hangHoa);
            setComboBoxNCC(hangHoa);
            jtfTenHH.setText(hangHoa.getTenHang());
            jtfHinhAnh.setText(hangHoa.getHinhAnh());
            jtfDVT.setText(hangHoa.getdVT());
            jtfGiaBan.setText(hangHoa.getGiaBan() + "");
            jtfHeSo.setText(hangHoa.getHeSo() + "");
            jtfGiaNhap.setText(hangHoa.getGiaNhap() + "");
            jtfHinhAnh.setText(hangHoa.getHinhAnh());
            jtfSoLuongTon.setText(hangHoa.getSoLuongTon() + "");
        } else {
            String mahang = generateMaHang();
            jtfMaHH.setText(mahang);
            setComboBoxNHH(null);
            setComboBoxNCC(null);
        }
    }

    public void setComboBoxNCC(HangHoa hangHoa) {
        DefaultComboBoxModel<NhaCungCap> model = new DefaultComboBoxModel<>();
        List<NhaCungCap> listNCC = NhaCungCapDAO.getInstance().getListNhaCungCap(1);

        for (NhaCungCap ncc : listNCC) {
            model.addElement(ncc);
        }

        if (hangHoa != null) {
            NhaCungCap nhacungcap = NhaCungCapDAO.getInstance().getNhaCungCap(hangHoa.getMaNCC());
            model.setSelectedItem(nhacungcap);
        }
        jcbNhaCC.setModel(model);
    }

    public void clearForm() {
        String mahang = generateMaHang();
        jtfMaHH.setText(mahang);
        jtfTenHH.setText("");
        jtfHinhAnh.setText("");
        jtfDVT.setText("");
        jtfHeSo.setText("");
        jtfGiaNhap.setText("");
        jtfHinhAnh.setText("");
        jtfSoLuongTon.setText("");
        jtfGiaBan.setText("");
    }

    public void setComboBoxNHH(HangHoa hangHoa) {
        DefaultComboBoxModel<NhomHang> model = new DefaultComboBoxModel<>();
        List<NhomHang> listNH = NhomHangDAO.getInstance().getListNhomHang();

        for (NhomHang nhomhang : listNH) {
            model.addElement(nhomhang);
        }

        if (hangHoa != null) {
            NhomHang nhomhang = NhomHangDAO.getInstance().getNhomHang(hangHoa.getMaNhomHang());
            model.setSelectedItem(nhomhang);
        }
        jcbNhomHH.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinHangHoa = new javax.swing.JPanel();
        jlbMaHH = new javax.swing.JLabel();
        jtfMaHH = new javax.swing.JTextField();
        jlbNhomHH = new javax.swing.JLabel();
        jlbNhaCC = new javax.swing.JLabel();
        jlbTenHH = new javax.swing.JLabel();
        jtfTenHH = new javax.swing.JTextField();
        jcbNhomHH = new javax.swing.JComboBox<>();
        jcbNhaCC = new javax.swing.JComboBox<>();
        jlbDVT = new javax.swing.JLabel();
        jtfDVT = new javax.swing.JTextField();
        jlbGiaBan = new javax.swing.JLabel();
        jtfHeSo = new javax.swing.JTextField();
        jlbHeSo = new javax.swing.JLabel();
        jtfGiaNhap = new javax.swing.JTextField();
        jlbGiaNhap = new javax.swing.JLabel();
        jlbHinhAnh = new javax.swing.JLabel();
        jtfHinhAnh = new javax.swing.JTextField();
        jlbSoLuongTon = new javax.swing.JLabel();
        jtfSoLuongTon = new javax.swing.JTextField();
        btnChonAnh = new javax.swing.JButton();
        jtfGiaBan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbHinhAnhSP = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jpnThongTinHangHoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hàng hóa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinHangHoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbMaHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaHH.setText("Mã hàng hóa");

        jtfMaHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfMaHH.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfMaHH.setEnabled(false);

        jlbNhomHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbNhomHH.setText("Nhóm hàng hóa");

        jlbNhaCC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbNhaCC.setText("Nhà cung cấp");

        jlbTenHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTenHH.setText("Tên hàng hóa");

        jtfTenHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jcbNhomHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jcbNhaCC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDVT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDVT.setText("Đơn vị tính");

        jtfDVT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbGiaBan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaBan.setText("Giá bán");

        jtfHeSo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfHeSo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfHeSoFocusLost(evt);
            }
        });

        jlbHeSo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbHeSo.setText("Hệ số");

        jtfGiaNhap.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfGiaNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfGiaNhapFocusLost(evt);
            }
        });

        jlbGiaNhap.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaNhap.setText("Giá nhập");

        jlbHinhAnh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbHinhAnh.setText("Hình Ảnh");

        jtfHinhAnh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbSoLuongTon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSoLuongTon.setText("Số lượng tồn");

        jtfSoLuongTon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfSoLuongTon.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        btnChonAnh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-openfolder.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        jtfGiaBan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfGiaBan.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfGiaBan.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("(*)");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(*)");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("(*)");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(*)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("(*)");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("(*)");

        javax.swing.GroupLayout jpnThongTinHangHoaLayout = new javax.swing.GroupLayout(jpnThongTinHangHoa);
        jpnThongTinHangHoa.setLayout(jpnThongTinHangHoaLayout);
        jpnThongTinHangHoaLayout.setHorizontalGroup(
            jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbMaHH)
                                    .addComponent(jlbTenHH)
                                    .addComponent(jlbHinhAnh)
                                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                        .addComponent(jlbNhaCC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                        .addComponent(jlbNhomHH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addComponent(jlbHinhAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfHinhAnh, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbNhaCC, 0, 271, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnThongTinHangHoaLayout.createSequentialGroup()
                                    .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)))
                            .addComponent(jcbNhomHH, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addComponent(jlbGiaNhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addComponent(jlbSoLuongTon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                                .addComponent(jlbHeSo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jlbGiaBan)
                            .addComponent(jlbDVT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jpnThongTinHangHoaLayout.setVerticalGroup(
            jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMaHH)
                            .addComponent(jtfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbGiaBan))
                        .addGap(11, 11, 11)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenHH)
                            .addComponent(jtfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jlbHeSo)
                            .addComponent(jLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNhaCC)
                            .addComponent(jcbNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNhomHH)
                            .addComponent(jcbNhomHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbHinhAnh)
                            .addComponent(jlbDVT))
                        .addGap(10, 10, 10)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbHinhAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnThongTinHangHoaLayout.createSequentialGroup()
                        .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtfHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbGiaNhap)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jpnThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSoLuongTon)
                            .addComponent(jtfSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addComponent(jtfDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        btnLuu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-save.png"))); // NOI18N
        btnLuu.setText("Lưu dữ liệu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongTinHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThongTinHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        HangHoa hanghoa = new HangHoa();
        if (validateInput()) {
            hanghoa.setMaHang(jtfMaHH.getText());
            NhomHang selectedNhomHang = (NhomHang) jcbNhomHH.getSelectedItem();
            hanghoa.setMaNhomHang(selectedNhomHang.getMaNhomHang());
            NhaCungCap selectedNhaCungCap = (NhaCungCap) jcbNhaCC.getSelectedItem();
            hanghoa.setMaNCC(selectedNhaCungCap.getMaNCC());
            hanghoa.setTenHang(jtfTenHH.getText().trim());
            hanghoa.setHinhAnh(jtfHinhAnh.getText());
            hanghoa.setdVT(jtfDVT.getText());
            hanghoa.setHeSo(Double.parseDouble(jtfHeSo.getText()));
            hanghoa.setGiaNhap(Double.parseDouble(jtfGiaNhap.getText()));
            hanghoa.setSoLuongTon(Double.parseDouble(jtfSoLuongTon.getText()));
            if (flag == 1) {
                int kq = HangHoaDAO.getInstance().insertHangHoa(hanghoa);
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Thêm hàng hóa", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
//                if (kq > 0) {
//
//                } else {
//                    JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Thêm hàng hóa", JOptionPane.WARNING_MESSAGE);
//                }
            } else {
                hanghoa.setMaHang(jtfMaHH.getText());
                int kq = HangHoaDAO.getInstance().updateHangHoa(hanghoa);
                JOptionPane.showMessageDialog(this, "Sửa thành công!", "Sửa hàng hóa", JOptionPane.INFORMATION_MESSAGE);
//                if (kq > 0) {
//                } else {
//                    JOptionPane.showMessageDialog(this, "Sửa thất bại!", "Sửa hàng hóa", JOptionPane.WARNING_MESSAGE);
//                }
            }
            hangHoaPanel.LoadHHVaoTable(null, null, null, 1, null);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private boolean validateInput() {
        if (jtfTenHH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin tên hàng", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfTenHH.requestFocus();
            return false;
        } else if (jtfHeSo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin hệ số", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfHeSo.requestFocus();
            return false;
        } else if (jtfGiaNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin giá nhập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfGiaNhap.requestFocus();
            return false;

        } else if (jtfSoLuongTon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin số lượng tồn", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfSoLuongTon.requestFocus();
            return false;
        } else {
            if (jtfDVT.getText().isEmpty()) {
                jtfDVT.setText("Kg");
            }
            if (jtfHinhAnh.getText().isEmpty()) {
                jtfHinhAnh.setText("Chưa xác định");
            }
        }
        return true;

    }

    private void setImageIcon(String imageName) {
        ImageIcon image = new ImageIcon("src\\Images\\" + imageName);
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(jlbHinhAnhSP.getWidth(), jlbHinhAnhSP.getHeight(), im.SCALE_SMOOTH));
        jlbHinhAnhSP.setIcon(icon);
    }

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        File defaultDirectory = new File("src\\Images\\");
        fileChooser.setCurrentDirectory(defaultDirectory);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            String[] string = path.split("\\\\");
            String fileName = string[string.length - 2] + "\\" + string[string.length - 1];
            jtfHinhAnh.setText(fileName);
            setImageIcon(jtfHinhAnh.getText());
        }
    }//GEN-LAST:event_btnChonAnhActionPerformed
    public void setGiaBan() {
        if (!jtfHeSo.getText().isEmpty() && !jtfGiaNhap.getText().isEmpty()) {
            Double heso = Double.parseDouble(jtfHeSo.getText());
            Double gianhap = Double.parseDouble(jtfGiaNhap.getText());
            Double giaban = gianhap * heso;
            jtfGiaBan.setText(giaban + "");
        }
    }
    private void jtfGiaNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfGiaNhapFocusLost
        // TODO add your handling code here:
        setGiaBan();
    }//GEN-LAST:event_jtfGiaNhapFocusLost

    private void jtfHeSoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfHeSoFocusLost
        // TODO add your handling code here:
        setGiaBan();
    }//GEN-LAST:event_jtfHeSoFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<NhaCungCap> jcbNhaCC;
    private javax.swing.JComboBox<NhomHang> jcbNhomHH;
    private javax.swing.JLabel jlbDVT;
    private javax.swing.JLabel jlbGiaBan;
    private javax.swing.JLabel jlbGiaNhap;
    private javax.swing.JLabel jlbHeSo;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbHinhAnhSP;
    private javax.swing.JLabel jlbMaHH;
    private javax.swing.JLabel jlbNhaCC;
    private javax.swing.JLabel jlbNhomHH;
    private javax.swing.JLabel jlbSoLuongTon;
    private javax.swing.JLabel jlbTenHH;
    private javax.swing.JPanel jpnThongTinHangHoa;
    private javax.swing.JTextField jtfDVT;
    private javax.swing.JTextField jtfGiaBan;
    private javax.swing.JTextField jtfGiaNhap;
    private javax.swing.JTextField jtfHeSo;
    private javax.swing.JTextField jtfHinhAnh;
    private javax.swing.JTextField jtfMaHH;
    private javax.swing.JTextField jtfSoLuongTon;
    private javax.swing.JTextField jtfTenHH;
    // End of variables declaration//GEN-END:variables
}
