/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietHoaDonDAO;
import DAO.HangHoaDAO;
import DTO.ChiTietHoaDon;
import DTO.HangHoa;
import DTO.HoaDon;
import Main.FontOptionPane;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class HoaDonJFrame extends javax.swing.JFrame {

    private ArrayList<ChiTietHoaDon> listCTHD = null;
    private HoaDonJPanel HoaDonJPanel;

    /**
     * Creates new form HoaDonJFrame
     */
    public HoaDonJFrame(HoaDon hd, HoaDonJPanel HoaDonJPanel) {
        initComponents();
        this.listCTHD = ChiTietHoaDonDAO.getInstance().getListCTHD(hd.getMaHD());
        setView(hd);
        LoadCTHDVaoTable(jtCTHoaDon, jspCTHoaDon);
        this.HoaDonJPanel = HoaDonJPanel;
        FontOptionPane.setUIFont();
    }

    public void setView(HoaDon hd) {
        if (hd != null) {
            jtfMaHD.setText(hd.getMaHD());
            jtfMaKH.setText(hd.getMaKH());
            jtfMaNV.setText(hd.getMaNV());
            jtfNgayTao.setText(hd.getNgayTao() + "");
            jtfTongTien.setText(hd.getTongTien() + "");
        }
    }

    void LoadCTHDVaoTable(JTable jt, JScrollPane jsp) {
        String[] header = {"Mã hàng hóa", "Tên hàng hóa", "Số lượng", "Đơn vị tính", "Đơn giá", "Thành tiên"};
        if (jt == null && jsp == null) {
            jt = jtCTHoaDon;
            jsp = jspCTHoaDon;
        }

        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        for (ChiTietHoaDon cthd : listCTHD) {
            Object[] row = {cthd.getMaHang(), cthd.getTenHang(), cthd.getSoLuong(), cthd.getDVT(), cthd.getDonGia(), cthd.getThanhTien()};
            modelTableDb.addRow(row);
        }

        TableRowSorter<TableModel> rowSorter = null;

        jt.setModel(modelTableDb);
        jt.setRowSorter(rowSorter);

        jt.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jt.setFont(new Font("Arial", Font.PLAIN, 14));
        jt.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jt.setRowHeight(50);
        jt.validate();
        jt.repaint();

        jsp.setPreferredSize(new Dimension(1350, 400));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinKhachHang = new javax.swing.JPanel();
        jspCTHoaDon = new javax.swing.JScrollPane();
        jtCTHoaDon = new javax.swing.JTable();
        jlbMaKH = new javax.swing.JLabel();
        jtfMaHD = new javax.swing.JTextField();
        jlbTenKH = new javax.swing.JLabel();
        jlbSDT = new javax.swing.JLabel();
        jtfMaKH = new javax.swing.JTextField();
        jlbDiaChi = new javax.swing.JLabel();
        jtfNgayTao = new javax.swing.JTextField();
        jtfMaNV = new javax.swing.JTextField();
        jlbDiaChi1 = new javax.swing.JLabel();
        jtfTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspCTHoaDon.setViewportView(jtCTHoaDon);

        jlbMaKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaKH.setText("Mã hóa đơn");

        jtfMaHD.setEditable(false);
        jtfMaHD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfMaHD.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jlbTenKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTenKH.setText("Mã khách hàng");

        jlbSDT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSDT.setText("Mã nhân viên");

        jtfMaKH.setEditable(false);
        jtfMaKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDiaChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDiaChi.setText("Ngày tạo");

        jtfNgayTao.setEditable(false);
        jtfNgayTao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jtfMaNV.setEditable(false);
        jtfMaNV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDiaChi1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDiaChi1.setText("Tổng tiền");

        jtfTongTien.setEditable(false);
        jtfTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jpnThongTinKhachHangLayout = new javax.swing.GroupLayout(jpnThongTinKhachHang);
        jpnThongTinKhachHang.setLayout(jpnThongTinKhachHangLayout);
        jpnThongTinKhachHangLayout.setHorizontalGroup(
            jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                        .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTenKH)
                            .addComponent(jlbMaKH)
                            .addComponent(jlbSDT))
                        .addGap(50, 50, 50)
                        .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jtfMaKH)
                            .addComponent(jtfMaHD))
                        .addGap(50, 50, 50)
                        .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(jlbDiaChi)
                                .addGap(77, 77, 77)
                                .addComponent(jtfNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(jlbDiaChi1)
                                .addGap(77, 77, 77)
                                .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jspCTHoaDon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );
        jpnThongTinKhachHangLayout.setVerticalGroup(
            jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaKH)
                    .addComponent(jtfNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDiaChi))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbDiaChi1))
                    .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbTenKH)
                        .addComponent(jtfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jspCTHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThongTinKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThongTinKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbDiaChi1;
    private javax.swing.JLabel jlbMaKH;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbTenKH;
    private javax.swing.JPanel jpnThongTinKhachHang;
    private javax.swing.JScrollPane jspCTHoaDon;
    private javax.swing.JTable jtCTHoaDon;
    private javax.swing.JTextField jtfMaHD;
    private javax.swing.JTextField jtfMaKH;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfNgayTao;
    private javax.swing.JTextField jtfTongTien;
    // End of variables declaration//GEN-END:variables
}
