/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.KhachHangDAO;
import DTO.KhachHang;
import Main.FontOptionPane;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class KhachHangJFrame extends javax.swing.JFrame {

    private KhachHangJPanel KhachHangPanel;

    public JButton getBtnLuu() {
        return btnLuu;
    }
    /**
     * Creates new form KhachHangJFrame
     */
    int flag = 0;

    public KhachHangJFrame(KhachHang kh, KhachHangJPanel KhachHangPanel, int flag) {
        initComponents();
        setView(kh);
        this.flag = flag;
        this.KhachHangPanel = KhachHangPanel;
        FontOptionPane.setUIFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinKhachHang = new javax.swing.JPanel();
        jlbMaKH = new javax.swing.JLabel();
        jtfMaKH = new javax.swing.JTextField();
        jlbTenKH = new javax.swing.JLabel();
        jlbSDT = new javax.swing.JLabel();
        jtfTenKH = new javax.swing.JTextField();
        jlbDiaChi = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jtfSDT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbMaKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaKH.setText("Mã khách hàng");

        jtfMaKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfMaKH.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfMaKH.setEnabled(false);

        jlbTenKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTenKH.setText("Tên khách hàng");

        jlbSDT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSDT.setText("Số điện thoại");

        jtfTenKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDiaChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDiaChi.setText("Địa chỉ");

        jtfDiaChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jtfSDT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("(*)");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(*)");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("(*)");

        javax.swing.GroupLayout jpnThongTinKhachHangLayout = new javax.swing.GroupLayout(jpnThongTinKhachHang);
        jpnThongTinKhachHang.setLayout(jpnThongTinKhachHangLayout);
        jpnThongTinKhachHangLayout.setHorizontalGroup(
            jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(jlbMaKH)
                        .addGap(54, 54, 54)
                        .addComponent(jtfMaKH))
                    .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                        .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(jlbDiaChi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(jlbTenKH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(jlbSDT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(25, 25, 25)
                        .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(jtfTenKH)
                            .addComponent(jtfSDT))))
                .addGap(140, 140, 140))
        );
        jpnThongTinKhachHangLayout.setVerticalGroup(
            jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhachHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaKH))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbTenKH)
                        .addComponent(jtfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(jtfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDiaChi)
                    .addComponent(jLabel3))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnLuu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-save.png"))); // NOI18N
        btnLuu.setText("Lưu dữ liệu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnThongTinKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        KhachHang kh = new KhachHang();
        if (validateInput()) {

            kh.setMaKH(jtfMaKH.getText());
            kh.setTenKH(jtfTenKH.getText().trim());
            kh.setSDT(jtfSDT.getText().trim());
            kh.setDiaChi(jtfDiaChi.getText());
            if (flag == 1) {
                KhachHangDAO.getInstance().insertKhachHang(kh);
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Thêm khách hàng", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                kh.setMaKH(jtfMaKH.getText());
                KhachHangDAO.getInstance().updateKhachHang(kh);
                JOptionPane.showMessageDialog(this, "Sửa thành công!", "Sửa khách hàng", JOptionPane.INFORMATION_MESSAGE);
            }
            if (this.KhachHangPanel != null) {
                KhachHangPanel.LoadKHVaoTable(null, null, null, 1);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    public void setView(KhachHang kh) {
        if (kh != null) {
            jtfMaKH.setText(kh.getMaKH() + "");
            jtfTenKH.setText(kh.getTenKH() + "");
            jtfSDT.setText(kh.getSDT() + "");
            jtfDiaChi.setText(kh.getDiaChi() + "");
        } else {
            String makh = generateMaKH();
            jtfMaKH.setText(makh);
        }
    }

    public void clearForm() {
        String makh = generateMaKH();
        jtfMaKH.setText(makh);
        jtfTenKH.setText("");
        jtfSDT.setText("");
        jtfDiaChi.setText("");
    }

    public String generateMaKH() {
        KhachHang khachhang = KhachHangDAO.getInstance().getLastKhachHang();
        int sothutu = (Integer.parseInt(khachhang.getMaKH().substring(2)) + 1);
        String makh = "KH";
        if (sothutu < 10) {
            makh = "KH00";
        } else if (sothutu < 100) {
            makh = "KH0";
        }
        makh += sothutu;
        return makh;
    }

    private boolean validateInput() {
        if (jtfTenKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin tên khách hàng", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfTenKH.requestFocus();
            return false;
        } else if (jtfSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin số điện thoại", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfSDT.requestFocus();
            return false;
        } else if (jtfDiaChi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin địa chỉ", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfDiaChi.requestFocus();
            return false;
        }
        return true;

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbMaKH;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbTenKH;
    private javax.swing.JPanel jpnThongTinKhachHang;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfMaKH;
    private javax.swing.JTextField jtfSDT;
    private javax.swing.JTextField jtfTenKH;
    // End of variables declaration//GEN-END:variables
}
