/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietHoaDonDAO;
import DAO.HoaDonDAO;
import DTO.ChiTietHoaDon;
import DTO.HoaDon;
import DTO.KhachHang;
import DTO.SessionData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ThanhToanJFrame extends javax.swing.JFrame {

    public BanHangJPanel formbanhang = null;

    /**
     * Creates new form ThanhToanJFrame
     */
    public ThanhToanJFrame(BanHangJPanel banhang) {
        initComponents();
        this.formbanhang = banhang;
        setView();
    }

    public void setView() {
        jtfTongTien.setText(this.formbanhang.TongTien + "");
        jtfGiamGia.setText("0");
        jtfKhachCanTra.setText(this.formbanhang.TongTien + "");
        jlbTenNhanVien.setText(SessionData.getNv().getTenNV());
        String mahd = generateMaHD();
        jtfMaHD.setText(mahd);
        if (this.formbanhang.khachhang != null) {
            jlbKhachHang.setText(this.formbanhang.khachhang.getTenKH());
        } else {
            jlbKhachHang.setText("Khách Lẻ");
        }
        jtfKhachThanhToan.requestFocus();
    }

    public String generateMaHD() {
        HoaDon hoadon = HoaDonDAO.getInstance().getLastHoaDon();
        int sothutu = (Integer.parseInt(hoadon.getMaHD().substring(2)) + 1);       
        
        String mahd = "HD";
        if (sothutu < 10) {
            mahd = "HD00";
        } else if (sothutu < 100) {
            mahd = "HD0";
        }
        mahd += sothutu;
        return mahd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinHoaDon = new javax.swing.JPanel();
        jlbKhachHang = new javax.swing.JLabel();
        jlbTongTien = new javax.swing.JLabel();
        jtfMaHD = new javax.swing.JTextField();
        jlbKhachThanhToan = new javax.swing.JLabel();
        jtfKhachThanhToan = new javax.swing.JTextField();
        jlbGiaBan = new javax.swing.JLabel();
        jtfKhachCanTra = new javax.swing.JTextField();
        jlbGiaNhap = new javax.swing.JLabel();
        jlbSoLuongTon = new javax.swing.JLabel();
        jtfTongTien = new javax.swing.JTextField();
        jtfGiamGia = new javax.swing.JTextField();
        jtfTienThua = new javax.swing.JTextField();
        jlbDVT1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlbTongTien1 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jlbMaHH1 = new javax.swing.JLabel();
        jlbTenNhanVien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbKhachHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbKhachHang.setText("Khách lẻ");

        jlbTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTongTien.setText("Mã hóa đơn");

        jtfMaHD.setEditable(false);
        jtfMaHD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbKhachThanhToan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbKhachThanhToan.setText("Khách thanh toán");

        jtfKhachThanhToan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfKhachThanhToan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfKhachThanhToanFocusLost(evt);
            }
        });

        jlbGiaBan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaBan.setText("Giảm giá");

        jtfKhachCanTra.setEditable(false);
        jtfKhachCanTra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbGiaNhap.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaNhap.setText("Khách cần trả");

        jlbSoLuongTon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSoLuongTon.setText("Tổng tiền");

        jtfTongTien.setEditable(false);
        jtfTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfTongTien.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jtfGiamGia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfGiamGia.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfGiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfGiamGiaFocusLost(evt);
            }
        });

        jtfTienThua.setEditable(false);
        jtfTienThua.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDVT1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDVT1.setText("Tiền thừa trả khách");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("%");

        jlbTongTien1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTongTien1.setText("Tên khách hàng");

        javax.swing.GroupLayout jpnThongTinHoaDonLayout = new javax.swing.GroupLayout(jpnThongTinHoaDon);
        jpnThongTinHoaDon.setLayout(jpnThongTinHoaDonLayout);
        jpnThongTinHoaDonLayout.setHorizontalGroup(
            jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinHoaDonLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTongTien)
                            .addComponent(jlbSoLuongTon))
                        .addGap(379, 379, 379))
                    .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                                .addComponent(jlbGiaBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnThongTinHoaDonLayout.createSequentialGroup()
                                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbGiaNhap)
                                    .addComponent(jlbKhachThanhToan)
                                    .addComponent(jlbDVT1)
                                    .addComponent(jlbTongTien1))
                                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfKhachCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlbKhachHang)
                                            .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtfKhachThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50))))
        );
        jpnThongTinHoaDonLayout.setVerticalGroup(
            jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHoaDonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbKhachHang)
                    .addComponent(jlbTongTien1))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTongTien)
                    .addComponent(jtfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSoLuongTon)
                    .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaBan)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfKhachCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaNhap))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfKhachThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKhachThanhToan))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDVT1))
                .addGap(20, 20, 20))
        );

        btnThanhToan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-payments.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jlbMaHH1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaHH1.setText("Nhân viên: ");

        jlbTenNhanVien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbTenNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbMaHH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTenNhanVien))
                    .addComponent(jpnThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaHH1)
                    .addComponent(jlbTenNhanVien))
                .addGap(31, 31, 31)
                .addComponent(jpnThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setTienSauGiamGia() {
        double tongTienSauGiam = this.formbanhang.TongTien;
        if (!jtfGiamGia.getText().isEmpty()) {
            double giamGia = Double.parseDouble(jtfGiamGia.getText());
            if (giamGia < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giảm giá lớn hơn hoặc bằng 0%", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jtfGiamGia.setText("0");
            } else {
                tongTienSauGiam = this.formbanhang.TongTien - (this.formbanhang.TongTien * (giamGia / 100));
            }
        } else {
            tongTienSauGiam = this.formbanhang.TongTien;
        }
        jtfKhachCanTra.setText(tongTienSauGiam + "");
    }

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if (jtfKhachCanTra.getText().trim().isEmpty()) {
            setTienSauGiamGia();
        }
        if (jtfKhachThanhToan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền khách thanh toán", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfKhachThanhToan.requestFocus();
        } else {
            String MaKH = null;
            if (this.formbanhang.khachhang != null) {
                MaKH = this.formbanhang.khachhang.getMaKH();
            }
            HoaDon hd = new HoaDon(jtfMaHD.getText(), SessionData.getNv().getMaNV(), MaKH, this.formbanhang.TongTien);
            HoaDonDAO.getInstance().insertHoaDon(hd);
            for (ChiTietHoaDon cthd : this.formbanhang.listCTHD) {
                cthd.setMaHD(hd.getMaHD());
                ChiTietHoaDonDAO.getInstance().insertChiTietHoaDon(cthd);
            }
            JOptionPane.showMessageDialog(this, "Thanh toán thành công!!", "Thanh toán", JOptionPane.INFORMATION_MESSAGE);
            if (this.formbanhang.listCTHD != null) {
               this.formbanhang.listCTHD = null;
               this.formbanhang.LoadCTHDVaoTable(null, null, null);
               this.formbanhang.tinhTongTien(this.formbanhang.listCTHD);
            }
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed
    private void jtfGiamGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfGiamGiaFocusLost
        // TODO add your handling code here:
        setTienSauGiamGia();
    }//GEN-LAST:event_jtfGiamGiaFocusLost

    private void jtfKhachThanhToanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfKhachThanhToanFocusLost
        // TODO add your handling code here:
        double TienThua = 0;
        if (!jtfKhachThanhToan.getText().isEmpty()) {
            double khachThanhToan = Double.parseDouble(jtfKhachThanhToan.getText());
            double tongTienSauGiam = Double.parseDouble(jtfKhachCanTra.getText());
            double khachCanTra = Double.parseDouble(jtfKhachCanTra.getText());
            if (khachThanhToan < khachCanTra) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền khách thanh toán lớn hơn hoặc bằng số tiền khách cần trả!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jtfKhachThanhToan.requestFocus();
            } else {
                TienThua = khachThanhToan - tongTienSauGiam;
            }
        }
        jtfTienThua.setText(TienThua + "");
    }//GEN-LAST:event_jtfKhachThanhToanFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbDVT1;
    private javax.swing.JLabel jlbGiaBan;
    private javax.swing.JLabel jlbGiaNhap;
    private javax.swing.JLabel jlbKhachHang;
    private javax.swing.JLabel jlbKhachThanhToan;
    private javax.swing.JLabel jlbMaHH1;
    private javax.swing.JLabel jlbSoLuongTon;
    private javax.swing.JLabel jlbTenNhanVien;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JLabel jlbTongTien1;
    private javax.swing.JPanel jpnThongTinHoaDon;
    private javax.swing.JTextField jtfGiamGia;
    private javax.swing.JTextField jtfKhachCanTra;
    private javax.swing.JTextField jtfKhachThanhToan;
    private javax.swing.JTextField jtfMaHD;
    private javax.swing.JTextField jtfTienThua;
    private javax.swing.JTextField jtfTongTien;
    // End of variables declaration//GEN-END:variables
}
