/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietPhieuNhapDAO;
import DAO.PhieuNhapDAO;
import DTO.ChiTietPhieuNhap;
import DTO.NhaCungCap;
import DTO.NhanVien;
import DTO.PhieuNhap;
import DTO.SessionData;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Quang
 */
public class ThanhToanNhapHangJFrame extends javax.swing.JFrame {

    
    private float TongTien;
    private NhaCungCap ncc;
    public ArrayList<ChiTietPhieuNhap> listCTPN = null;
    /**
     * Creates new form ThanhToanNhapHangJFrame
     */
    public ThanhToanNhapHangJFrame(float tongTien, NhaCungCap ncc, ArrayList<ChiTietPhieuNhap> listCTPN) {
        initComponents();
        this.TongTien = tongTien;
        this.ncc = ncc;
        this.listCTPN = listCTPN;
        setView();
    }

    public void setView() {
        jtfTongTien.setText(this.TongTien + "");
        jtfGiamGia.setText("0");
        jtfNVCanTra.setText(this.TongTien + "");
        jlbEmpName.setText(SessionData.getNv().getTenNV());
        String maPN = generateMaPN();
        jtfMaPN.setText(maPN);        
        jtfNVThanhToan.requestFocus();
    }
    public String generateMaPN() {
        PhieuNhap pn = PhieuNhapDAO.getInstance().getLastPhieuNhap();
        int sothutu = (Integer.parseInt(pn.getMaPN().substring(2)) + 1);
        String maPN = "PN";
        if (sothutu < 10) {
            maPN = "PN00";
        } else if (sothutu < 100) {
            maPN = "PN0";
        }
        maPN += sothutu;
        return maPN;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinPhieuNhap = new javax.swing.JPanel();
        jlbEmpName = new javax.swing.JLabel();
        jlbTongTien8 = new javax.swing.JLabel();
        jtfMaPN = new javax.swing.JTextField();
        jlbKhachThanhToan4 = new javax.swing.JLabel();
        jtfNVThanhToan = new javax.swing.JTextField();
        jlbGiaBan4 = new javax.swing.JLabel();
        jtfNVCanTra = new javax.swing.JTextField();
        jlbGiaNhap4 = new javax.swing.JLabel();
        jlbSoLuongTon4 = new javax.swing.JLabel();
        jtfTongTien = new javax.swing.JTextField();
        jtfGiamGia = new javax.swing.JTextField();
        jtfTienThua = new javax.swing.JTextField();
        jlbDVT5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbTongTien9 = new javax.swing.JLabel();
        jbtnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinPhieuNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinPhieuNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbEmpName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jlbTongTien8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTongTien8.setText("Mã phiếu nhập");

        jtfMaPN.setEditable(false);
        jtfMaPN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbKhachThanhToan4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbKhachThanhToan4.setText("Nhân viên thanh toán");

        jtfNVThanhToan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfNVThanhToan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNVThanhToanFocusLost(evt);
            }
        });

        jlbGiaBan4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaBan4.setText("Giảm giá");

        jtfNVCanTra.setEditable(false);
        jtfNVCanTra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbGiaNhap4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbGiaNhap4.setText("Nhân viên cần trả");

        jlbSoLuongTon4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSoLuongTon4.setText("Tổng tiền");

        jtfTongTien.setEditable(false);
        jtfTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfTongTien.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jtfGiamGia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfGiamGia.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jtfGiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfGiamGiaFocusLost(evt);
            }
        });

        jtfTienThua.setEditable(false);
        jtfTienThua.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbDVT5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDVT5.setText("Tiền thừa nhận");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("%");

        jlbTongTien9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTongTien9.setText("Tên nhân viên");

        javax.swing.GroupLayout jpnThongTinPhieuNhapLayout = new javax.swing.GroupLayout(jpnThongTinPhieuNhap);
        jpnThongTinPhieuNhap.setLayout(jpnThongTinPhieuNhapLayout);
        jpnThongTinPhieuNhapLayout.setHorizontalGroup(
            jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinPhieuNhapLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                        .addComponent(jlbSoLuongTon4)
                        .addGap(417, 417, 417))
                    .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                        .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                                .addComponent(jlbGiaBan4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnThongTinPhieuNhapLayout.createSequentialGroup()
                                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbGiaNhap4)
                                    .addComponent(jlbKhachThanhToan4)
                                    .addComponent(jlbDVT5)
                                    .addComponent(jlbTongTien8)
                                    .addComponent(jlbTongTien9))
                                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfNVCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtfNVThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50))))
        );
        jpnThongTinPhieuNhapLayout.setVerticalGroup(
            jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbTongTien9, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTongTien8)
                    .addComponent(jtfMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSoLuongTon4)
                    .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaBan4)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNVCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaNhap4))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNVThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKhachThanhToan4))
                .addGap(20, 20, 20)
                .addGroup(jpnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDVT5))
                .addGap(20, 20, 20))
        );

        jbtnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-payments.png"))); // NOI18N
        jbtnThanhToan.setText("Thanh toán");
        jbtnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jbtnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jpnThongTinPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(jbtnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jpnThongTinPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNVThanhToanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNVThanhToanFocusLost
        // TODO add your handling code here:
        double TienThua = 0;
        if (!jtfNVThanhToan.getText().isEmpty()) {
            double NVThanhToan = Double.parseDouble(jtfNVThanhToan.getText());
            double tongTienSauGiam = Double.parseDouble(jtfNVCanTra.getText());
            double NVCanTra = Double.parseDouble(jtfNVCanTra.getText());
            if (NVThanhToan < NVCanTra) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền thanh toán lớn hơn hoặc bằng số tiền khách cần trả!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jtfNVThanhToan.requestFocus();
            } else {
                TienThua = NVThanhToan - tongTienSauGiam;
            }
        }
        jtfTienThua.setText(TienThua + "");
    }//GEN-LAST:event_jtfNVThanhToanFocusLost

    private void setTienSauGiamGia() {
        double tongTienSauGiam = this.TongTien;
        if (!jtfGiamGia.getText().isEmpty()) {
            double giamGia = Double.parseDouble(jtfGiamGia.getText());
            if (giamGia < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giảm giá lớn hơn hoặc bằng 0%", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jtfGiamGia.setText("0");
            } else {
                tongTienSauGiam = this.TongTien - (this.TongTien * (giamGia / 100));
            }
        } else {
            tongTienSauGiam = this.TongTien;
        }
        jtfNVCanTra.setText(tongTienSauGiam + "");
    }
    
    private void jtfGiamGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfGiamGiaFocusLost
        // TODO add your handling code here:
        setTienSauGiamGia();
    }//GEN-LAST:event_jtfGiamGiaFocusLost

    private void jbtnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThanhToanActionPerformed
        // TODO add your handling code here:
        if (jtfNVCanTra.getText().trim().isEmpty()) {
            setTienSauGiamGia();
        }
        if (jtfNVThanhToan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền cần thanh toán", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            jtfNVThanhToan.requestFocus();
        } else {
            PhieuNhap pn = new PhieuNhap(jtfMaPN.getText(), SessionData.getNv().getMaNV(), this.ncc.getMaNCC(), this.TongTien);
            PhieuNhapDAO.getInstance().insertPhieuNhap(pn);
            for (ChiTietPhieuNhap ctpn : this.listCTPN) {
                ctpn.setMaPN(pn.getMaPN());
                ChiTietPhieuNhapDAO.getInstance().insertChiTietPhieuNhap(ctpn);
            }
            JOptionPane.showMessageDialog(this, "Thanh toán thành công!!", "Thanh toán", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnThanhToan;
    private javax.swing.JLabel jlbDVT5;
    private javax.swing.JLabel jlbEmpName;
    private javax.swing.JLabel jlbGiaBan4;
    private javax.swing.JLabel jlbGiaNhap4;
    private javax.swing.JLabel jlbKhachThanhToan4;
    private javax.swing.JLabel jlbSoLuongTon4;
    private javax.swing.JLabel jlbTongTien8;
    private javax.swing.JLabel jlbTongTien9;
    private javax.swing.JPanel jpnThongTinPhieuNhap;
    private javax.swing.JTextField jtfGiamGia;
    private javax.swing.JTextField jtfMaPN;
    private javax.swing.JTextField jtfNVCanTra;
    private javax.swing.JTextField jtfNVThanhToan;
    private javax.swing.JTextField jtfTienThua;
    private javax.swing.JTextField jtfTongTien;
    // End of variables declaration//GEN-END:variables
}
