-- phân quyền
CREATE USER "CHNONGSAN" IDENTIFIED BY "123"
TEMPORARY TABLESPACE "TEMP";
GRANT "CONNECT" TO "CHNONGSAN";
GRANT "RESOURCE" TO "CHNONGSAN";
ALTER USER "CHNONGSAN" DEFAULT ROLE "CONNECT", "RESOURCE";
GRANT UNLIMITED TABLESPACE TO "CHNONGSAN";

CREATE USER ADMIN IDENTIFIED BY "admin123";
CREATE USER CUONG IDENTIFIED BY "123";
CREATE USER LINH IDENTIFIED BY "123";
CREATE USER MINH IDENTIFIED BY "123";

GRANT CREATE SESSION TO CUONG;
GRANT CREATE SESSION TO LINH;
GRANT CREATE SESSION TO MINH;
GRANT CREATE SESSION TO ADMIN;

GRANT SYSDBA TO ADMIN;






