CREATE TABLE nhomhang (
    ma_nhomhang    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_nhomhang   NVARCHAR2(50)
)

INSERT INTO "DAT"."NHOMHANG" (TEN_NHOMHANG) VALUES (N'Trái cây');

CREATE TABLE hanghoa 
(
    ma_hang       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nhomhang   INT,
    tenhang       NVARCHAR2(50),
    dvt           NVARCHAR2(20), 
    giaban NUMBER,
    gianhap NUMBER,
    hinhanh VARCHAR(50),
    soluongton INT,
    CONSTRAINT fk_hanhghoa_nhomhang FOREIGN KEY ( ma_nhomhang )
        REFERENCES nhomhang ( ma_nhomhang )
)

INSERT INTO "DAT"."HANGHOA" (MA_NHOMHANG, TENHANG, DVT, GIABAN, GIANHAP, HINHANH, SOLUONGTON) VALUES (1, N'Chu?i', 'Kg', 10000, 80000, 'chuoi.jpg', 10);

CREATE TABLE nhacungcap
(
        ma_ncc INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ten_ncc nvarchar2(50),
        sdt_ncc varchar(11),
        diachi nvarchar2(50)
)

CREATE TABLE nhanvien
(
    ma_nv INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_nv nvarchar2(50),
    sdt varchar(11),
    username varchar(30),
    password varchar(30),
    chuc_vu nvarchar2(50)
)

CREATE TABLE khachhang
(
    ma_kh INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_kh nvarchar2(50),
    sdt varchar(11),
    diachi nvarchar2(50)
)

CREATE TABLE hoadon
(
    ma_hd INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nv INT,
    ma_kh INT,
    ngay_tao Date,
    tongtien Number,
    CONSTRAINT fk_hoadon_nhanvien FOREIGN KEY ( ma_nv )
        REFERENCES nhanvien ( ma_nv ),
    CONSTRAINT fk_hoadon_khachhang FOREIGN KEY ( ma_kh )
        REFERENCES khachhang ( ma_kh )
)

CREATE TABLE chitiethoadon
(
    ma_hang INT,
    ma_hd INT,
    giaban number,
    soluong int,
    thanhtien number,
    constraint pk_chitiethoadon primary key (ma_hang, ma_hd),
    CONSTRAINT fk_chitiethoadon_mahang FOREIGN KEY ( ma_hang )
        REFERENCES hanghoa ( ma_hang ),
    CONSTRAINT fk_chitiethoadon_hoadon FOREIGN KEY ( ma_hd )
        REFERENCES hoadon ( ma_hd )
)

CREATE TABLE phieunhap
(
    ma_pn INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nv INT,
    ma_ncc INT,
    ngay_nhap Date,
    tongtien Number,
    CONSTRAINT fk_phieunhap_nhanvien FOREIGN KEY ( ma_nv )
        REFERENCES nhanvien ( ma_nv ),
    CONSTRAINT fk_phieunhap_nhacungcap FOREIGN KEY ( ma_ncc )
        REFERENCES nhacungcap ( ma_ncc ) 
)

CREATE TABLE chitietphieunhap
(
    ma_pn int,
    ma_hang int,
    gianhap number,
    soluong int,
    thanhtien number,
    constraint pk_chitietphieunhap primary key (ma_pn, ma_hang),
    CONSTRAINT fk_chitietphieunhap_mahang FOREIGN KEY ( ma_hang )
        REFERENCES hanghoa ( ma_hang ),
    CONSTRAINT fk_chitietphieunhap_phieunhap FOREIGN KEY ( ma_pn )
        REFERENCES phieunhap ( ma_pn ) 
)